[patch.crates-io.holo_hash]
branch = "develop-0.3"
git = "https://github.com/guillemcordoba/holochain"

[patch.crates-io.holochain]
branch = "develop-0.3"
git = "https://github.com/guillemcordoba/holochain"

[patch.crates-io.holochain_conductor_api]
branch = "develop-0.3"
git = "https://github.com/guillemcordoba/holochain"

[patch.crates-io.holochain_integrity_types]
branch = "develop-0.3"
git = "https://github.com/guillemcordoba/holochain"

[patch.crates-io.holochain_keystore]
branch = "develop-0.3"
git = "https://github.com/guillemcordoba/holochain"

[patch.crates-io.holochain_nonce]
branch = "develop-0.3"
git = "https://github.com/guillemcordoba/holochain"

[patch.crates-io.holochain_types]
branch = "develop-0.3"
git = "https://github.com/guillemcordoba/holochain"

[patch.crates-io.holochain_zome_types]
branch = "develop-0.3"
git = "https://github.com/guillemcordoba/holochain"

[patch.crates-io.kitsune_p2p_timestamp]
branch = "develop-0.3"
git = "https://github.com/guillemcordoba/holochain"

[patch.crates-io.mr_bundle]
branch = "develop-0.3"
git = "https://github.com/guillemcordoba/holochain"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
resolver = "2"
members = ["crates/dnas/*/zomes/coordinator/*", "crates/dnas/*/zomes/integrity/*", "src-tauri"]

[workspace.dependencies]
hdk = "0.3.1-rc.1"
hdi = "0.4.1-rc.1"
serde = "1.0"
serde_json = "1"

[workspace.dependencies.personal]
path = "crates/dnas/habits/zomes/coordinator/personal"

[workspace.dependencies.personal_integrity]
path = "crates/dnas/habits/zomes/integrity/personal"

[workspace.dependencies.holochain]
default-features = false
features = ["test_utils"]
version = "0.3.1-rc"
