export const positiveCol = "rgba(80, 227, 194, 0.9)";
export const positiveColLighter = "#edd837";
export const negativeCol = "rgba(155, 89, 182, 0.9)";
export const parentPositiveBorderCol = "rgba(80, 227, 194, 0.4)";
export const noNodeCol = "#888";
export const neutralCol = "#DADECD";

export const BASE_SCALE = 3.2;
export const FOCUS_MODE_SCALE = 3;
export const XS_LABEL_SCALE = 1.5;
export const LG_LABEL_SCALE = 2.5;
export const XS_BUTTON_SCALE = 2;
export const LG_BUTTON_SCALE = 3.2;
export const XS_NODE_RADIUS = 60;
export const LG_NODE_RADIUS = 70;
export const XS_LEVELS_HIGH = 4;
export const LG_LEVELS_HIGH = 6;
export const XS_LEVELS_WIDE = 4;
export const LG_LEVELS_WIDE = 2