[package]
name = "personal"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "personal"

[dependencies]
serde_json = { workspace = true }
hdk = { workspace = true }
serde = { workspace = true }
personal_integrity = { workspace = true } 