name: CI

on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v27

      - name: Set up cachix
        uses: cachix/cachix-action@v12
        with:
          name: holochain-ci

      - name: Restore cargo and build from cache
        uses: actions/cache/restore@v3
        with:
          path: |
            .cargo
            target
          key: ${{ runner.os }}-build-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install nix packages
        run: nix develop -c $SHELL -c "echo Nix packages installed"

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install vite
        run: nix develop -c $SHELL -c "pnpm i vite -D -w"

      - name: Build design system
        run: nix develop -c $SHELL -c "cd design-system && pnpm build"

      - name: Install JS packages
        run: nix develop -c $SHELL -c "pnpm i"

      - name: Build Happ
        run: nix develop -c $SHELL -c "pnpm run build:happ"

      - name: Test with tryorama
        run: nix develop -c $SHELL -c "pnpm test"